---
- name: 'Enable iptables'
  service: name=iptables state=started enabled=yes

- name: 'Open Apache firewall ports'
  command: lokkit --service=https
  changed_when: false

- name: 'Open IdP Backchannel port 8443 only when enabled'
  command: lokkit --port=8443:tcp
  changed_when: false
  when: enable_backchannel is defined and enable_backchannel=="true"

- name: 'Open SSH'
  command: lokkit --port=22:tcp
  changed_when: false
